from __future__ import annotations

"""Unified paper-final validation attempt-level CSV schema (Exp8–Exp15)."""

UNIFIED_ATTEMPT_FIELDS: list[str] = [
    "experiment_id",
    "condition",
    "method",
    "event_id",
    "run_id",
    "semantic_type",
    "source_id",
    "source_family",
    "benchmark_sha256",
    "method_sha256",
    "prompt_sha256",
    "oracle_candidate_id",
    "selected_candidate_id",
    "decision",
    "oracle_correct",
    "closure_pass",
    "strict_success",
    "wrong_select",
    "abstain",
    "failure_stage",
    "failure_reason",
    "m13_status",
    "m14_status",
    "m15_status",
    "ranking_status",
    "m16_status",
    "closure_status",
    "api_error",
    "timeout",
    "llm_calls",
    "input_tokens",
    "output_tokens",
    "total_tokens",
    "latency_ms",
    "random_seed",
    "timestamp",
]
